### PR TITLE
rough_guide_element

### PR DESCRIPTION
**Pull request by samuelorion**
Just a rough intro to setting up.

### CODE REVIEW

**Comment by dannycolin** [comment]
@SamGuay Can we not blindly merge PR please. ;)

**Comment by dannycolin** [comment]
@samuelorion Could you reopen a new PR with the same patch and add me as a reviewer?

**Comment by SamGuay** [comment]
I guess it's not too late to learn pull request etiquette :grimacing: . 

I did look at the code, but didnt think it through. We can iterate on the PR to produce a document of better quality. 

#lessonlearned

**Comment by samuelorion** [comment]
I have no idea what is going on lol Thanks both of you anyway :) #newbie

**Comment by dannycolin** [comment]
> I have no idea what is going on lol Thanks both of you anyway :) #newbie

You need to create a new PR exactly like this one.

**Pull request merged**
